### ISSUE TITLE
Please provide binaries for download

### ISSUE THREAD

**Issue by probonopd** [OpenICP-BR/ktApp#1]
Please provide binaries for download on GitHub Releases, thank you. I am especially interested in the AppImage for Linux.

**Comment by gjvnq** [comment]
I will do so as soon as I can get Travis CI to generate them.

**Comment by gjvnq** [comment]
Debian binaries are already available. See README.md

**Comment by probonopd** [comment]
Thanks, but as written above I am especially interested in the AppImage for Linux.
